# -*- coding: utf-8 -*-
"""9001作业.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k3MCr5Wjd9BGkwoqqWuODS_LvIptFiso
"""

"""
Mysterious Forest Adventure Game
Explore scenes through directional commands, trigger key events to clear the game！！！
"""
# scenes description
scenes = {
    "Entrance": {
        "description": "You stand at the entrance of the forest. In the damp fog, three paths are visible: East, South, and West.\nEast leads to the Misty Path, South to the Ancient Ruins, and West to the Quiet Lake.",
        "exits": {"east": "Misty Path", "south": "Ancient Ruins", "west": "Quiet Lake"}
    },
    "Misty Path": {
        "description": "The path is shrouded in thick fog, with the sound of cracking twigs underfoot. Ahead is a hollow tree, and a faint light shines from within.\n(Enter 'climb' to use the iron hook)",
        "exits": {"west": "Entrance", "climb": "Mountain Peak"}
    },
    "Mountain Peak": {
        "description": "After reaching the mountain peak, you discover a hidden staircase leading to the Magic Garden below.",
        "exits": {"down": "Magic Garden"}
    },
    "Magic Garden": {
        "description": "In the strange garden, the central fountain shimmers with light. After touching the fountain, the water recedes to reveal a key.",
        "exits": {"north": "Cliff", "take key": "Altar Entrance"}
    },
    "Altar Entrance": {
        "description": "A golden arch stands before you, with the glow of the altar visible beyond the door.",
        "exits": {"enter": "Altar"}
    },
    "Ancient Ruins": {
        "description": "Among the残破的stone walls stands an altar with a stone box featuring a keyhole.",
        "exits": {"north": "Entrance", "place key": "Altar"}
    },
    "Altar": {
        "description": "A column of light rises from the center of the altar, illuminating the entire forest! You've found the exit!",
        "is_win": True,
        "exits": {}
    },
    "Quiet Lake": {
        "description": "The calm lake reflects the moonlight, and a stone pavilion stands on a small island in the center.\n(Enter 'swim' to go to the island)",
        "exits": {"east": "Entrance", "swim": "Small Island"}
    },
    "Small Island": {
        "description": "Inside the stone pavilion, an ancient stone tablet bears a通关 incantation: Enter '解除封印' (解除封印 means '解除封印' in Chinese, kept as-is for the puzzle).",
        "exits": {"return": "Quiet Lake", "解除封印": "Altar"}
    }
}

player = {
    "current_scene": "Entrance",
    "has_key":
     False
}

def reset_game():
    """Reset game state"""
    player.update({
        "current_scene": "Entrance",
        "has_key": False
    })
    print("\n Game start!\n")


def print_scene():
    """Print current scene information"""
    if player["current_scene"] == "Altar":
        return  # Skip printing for win scene
    scene = scenes[player["current_scene"]]
    print(f"\n{'='*20} {player['current_scene']} {'='*20}")
    print(scene["description"])
    print("\nAvailable actions:", end="")

    for direction in scene["exits"]:
        if direction == "take key" and player["has_key"]:
            continue
        print(f" [{direction}]", end="")
    print()


def main():
    """Main game loop"""
    print("""
 * Mysterious Forest Adventure *
---------------------------
Objective: Find the altar and lift the seal to escape the forest!
Commands: Enter directions (east/south/west/north) or special commands (e.g., climb, take key)
After clearing the game, you can choose to start over
""")

    while True:

        if player["current_scene"] == "Altar":
            print("\n Congratulations! You've successfully escaped the mysterious forest!")
            reset_choice = input(" Would you like to start a new adventure? (y/n) ").strip().lower()
            if reset_choice == "y":
                reset_game()
            else:
                print("Thanks for playing! See you next time～")
                break
            continue

        print_scene()
        action = input("\nEnter command: ").strip().lower()
        current_scene = player["current_scene"]


        if action in scenes[current_scene].get("exits", {}):
            next_scene = scenes[current_scene]["exits"][action]


            if action == "climb":
                print("You use the iron hook to climb the cliff and reach the mountain peak!")
                player["current_scene"] = "Mountain Peak"

            elif action == "take key":
                print("You retrieve the key from the fountain, feeling a surge of magic!")
                player["has_key"] = True
                player["current_scene"] = "Altar Entrance"

            elif action == "place key":
                if player["has_key"]:
                    print("After inserting the key into the stone platform, the altar passage opens!")
                    player["current_scene"] = "Altar"
                else:
                    print(" You haven't obtained the key yet! Please go to the Magic Garden to find the key first.")
                    continue

            elif action == "swim":
                print("You swim strenuously to the small island and discover the mysterious stone tablet!")
                player["current_scene"] = "Small Island"

            elif action == "lift the seal":
                if current_scene == "Small Island":
                    print("You chant the incantation, and a dazzling light shines toward the altar!")
                    player["current_scene"] = "Altar"
                else:
                    print("The incantation is only valid in front of the stone tablet on the small island!")
                    continue

            else:
                player["current_scene"] = next_scene
            continue

        else:
            print(" Unknown command! Please enter a direction or special action (e.g., climb, take key)")


if __name__ == "__main__":
    main()